#ifndef RAIDS_MOB_DZSTRIKER_H
#define RAIDS_MOB_DZSTRIKER_H

#include "game.h"

#define DZSTRIKER_RENDER_COST                    (85)

#define DZSTRIKER_BASE_REACTION_TICKS						(0.25 * TPS)
#define DZSTRIKER_BASE_ATTACK_COOLDOWN_TICKS			(2 * TPS)
#define DZSTRIKER_BASE_EXPLODE_RADIUS						(5)
#define DZSTRIKER_MELEE_HIT_RADIUS								(0.5)
#define DZSTRIKER_EXPLODE_HIT_RADIUS							(5)
#define DZSTRIKER_MELEE_ATTACK_RADIUS						(5)

#define DZSTRIKER_TARGET_KEEP_CURRENT_FACTOR     (3)

#define DZSTRIKER_MAX_WALKABLE_SLOPE             (40 * MATH_DEG2RAD)
#define DZSTRIKER_BASE_STEP_HEIGHT								(2)
#define DZSTRIKER_TURN_RADIANS_PER_SEC           (90 * MATH_DEG2RAD)
#define DZSTRIKER_TURN_AIR_RADIANS_PER_SEC       (45 * MATH_DEG2RAD)
#define DZSTRIKER_MOVE_ACCELERATION              (25)
#define DZSTRIKER_MOVE_AIR_ACCELERATION          (5)

#define DZSTRIKER_ANIM_ATTACK_TICKS							(30)
#define DZSTRIKER_FLINCH_COOLDOWN_TICKS					(60 * 7)
#define DZSTRIKER_KNOCKBACK_MULTIPLIER				    (1.5)
#define DZSTRIKER_ACTION_COOLDOWN_TICKS					(30)
#define DZSTRIKER_RESPAWN_AFTER_TICKS						(60 * 30)
#define DZSTRIKER_BASE_COLL_RADIUS								(1.0)
#define DZSTRIKER_MAX_COLL_RADIUS								(4)
#define DZSTRIKER_AMBSND_MIN_COOLDOWN_TICKS    	(60 * 2)
#define DZSTRIKER_AMBSND_MAX_COOLDOWN_TICKS    	(60 * 3)
#define DZSTRIKER_FLINCH_PROBABILITY             (1.0)
#define DZSTRIKER_FLINCH_PROBABILITY_PWR_FACTOR  (0.1)

#define DZSTRIKER_PRIMARY_COLOR                  (0x00464443)
#define DZSTRIKER_GLOW_COLOR                     (0x80202020)
#define DZSTRIKER_LOD_COLOR                      (0x00808080)

enum DZStrikerTorsoAnimId
{
	DZSTRIKER_TORSO_ANIM_IDLE,
	DZSTRIKER_TORSO_ANIM_IDLE_SPIN_GUN,
	DZSTRIKER_TORSO_ANIM_IDLE_LOOK_LEFT_RIGHT,
	DZSTRIKER_TORSO_ANIM_AIM_GUN,
	DZSTRIKER_TORSO_ANIM_FIRE_GUN_LOOP,
	DZSTRIKER_TORSO_ANIM_FIRE_GUN_HIT_CELEBRATE,
	DZSTRIKER_TORSO_ANIM_AIM_SNIPER,
	DZSTRIKER_TORSO_ANIM_FIRE_SNIPER,
	DZSTRIKER_TORSO_ANIM_THROW_GRENADE,
	DZSTRIKER_TORSO_ANIM_MELEE_SWING,
	DZSTRIKER_TORSO_ANIM_JUMP,
	DZSTRIKER_TORSO_ANIM_FLINCH,
	DZSTRIKER_TORSO_ANIM_FLINCH_2,
	DZSTRIKER_TORSO_ANIM_FLINCH_3_BAD_ANIM,
	DZSTRIKER_TORSO_ANIM_DRIVE,
	DZSTRIKER_TORSO_ANIM_DRIVE_2,
	DZSTRIKER_TORSO_ANIM_DRIVE_FLINCH,
	DZSTRIKER_TORSO_ANIM_DRIVE_FLINCH_2,
};

enum DZStrikerLegsAnimId
{
	DZSTRIKER_LEGS_ANIM_IDLE,
	DZSTRIKER_LEGS_ANIM_WALK_FORWARD,
	DZSTRIKER_LEGS_ANIM_RUN_FORWARD,
	DZSTRIKER_LEGS_ANIM_WALK_BACKWARD,
	DZSTRIKER_LEGS_ANIM_JUMP,
	DZSTRIKER_LEGS_ANIM_THROW,
	DZSTRIKER_LEGS_ANIM_IDLE_2,
	DZSTRIKER_LEGS_ANIM_FLINCH_STEP_BACK,
	DZSTRIKER_LEGS_ANIM_FLINCH_JUMP_IN_AIR,
	DZSTRIKER_LEGS_ANIM_FLINCH_FALL_DOWN,
	DZSTRIKER_LEGS_ANIM_IDLE_3,
	DZSTRIKER_LEGS_ANIM_FLINCH,
	DZSTRIKER_LEGS_ANIM_FLYING,
	DZSTRIKER_LEGS_ANIM_KNEELING,
};

enum DZStrikerTorsoBangles {
	DZSTRIKER_TORSO_BANGLE_PISTOL =  	            (1 << 0),
	DZSTRIKER_TORSO_BANGLE_LEFT_CHEST =  	        (1 << 1),
	DZSTRIKER_TORSO_BANGLE_RIGHT_CHEST =  	      (1 << 2),
	DZSTRIKER_TORSO_BANGLE_RIGHT_CHEST_DAMAGED =  (1 << 3),
	DZSTRIKER_TORSO_BANGLE_LEFT_CHEST_DAMAGED =  	(1 << 4),
	DZSTRIKER_TORSO_BANGLE_SNIPER =  	            (1 << 8),
	DZSTRIKER_TORSO_BANGLE_BLASTER =  	          (1 << 9),
	DZSTRIKER_TORSO_BANGLE_HIDE_BODY =	          (1 << 15)
};

enum DZStrikerTorsoSubskeletonJoints
{
  DZSTRIKER_TORSO_SUBSKELETON_JOINT_GUN_CHAMBER = 0,
  DZSTRIKER_TORSO_SUBSKELETON_JOINT_LEFT_HAND,
  DZSTRIKER_TORSO_SUBSKELETON_JOINT_SNIPER_END,
  DZSTRIKER_TORSO_SUBSKELETON_JOINT_SNIPER_CHAMBER,
  DZSTRIKER_TORSO_SUBSKELETON_JOINT_ABDOMEN,
  DZSTRIKER_TORSO_SUBSKELETON_JOINT_RIGHT_ELBOW,
  DZSTRIKER_TORSO_SUBSKELETON_JOINT_RIGHT_SHOULDER,
  DZSTRIKER_TORSO_SUBSKELETON_JOINT_HEAD,
  DZSTRIKER_TORSO_SUBSKELETON_JOINT_CHEST,
};

enum DZStrikerLegsSubskeletonJoints
{
  DZSTRIKER_LEGS_SUBSKELETON_JOINT_HIPS = 0,
  DZSTRIKER_LEGS_SUBSKELETON_JOINT_LEFT_FOOT,
  DZSTRIKER_LEGS_SUBSKELETON_JOINT_RIGHT_FOOT,
};

enum DZStrikerAction
{
	DZSTRIKER_ACTION_SPAWN,
	DZSTRIKER_ACTION_IDLE,
	DZSTRIKER_ACTION_JUMP,
	DZSTRIKER_ACTION_WALK,
	DZSTRIKER_ACTION_FLINCH,
	DZSTRIKER_ACTION_BIG_FLINCH,
	DZSTRIKER_ACTION_LOOK_AT_TARGET,
  DZSTRIKER_ACTION_DIE,
	DZSTRIKER_ACTION_ATTACK,
	DZSTRIKER_ACTION_ROAM,
	DZSTRIKER_ACTION_STRAFE,
	DZSTRIKER_ACTION_AIM,
	DZSTRIKER_ACTION_FIRE,
};

enum DZStrikerBehaviorId
{
	DZSTRIKER_BEHAVIOR_NORMAL,
	DZSTRIKER_BEHAVIOR_HOLD_POSITION,
};

extern struct MobVTable DZStrikerVTable;

typedef struct DZStrikerMobVars {
  VECTOR HoldPosition;
  Moby* TorsoMoby;
  float TorsoRotation[3];
  float LastShotAtAnimT;
  char TorsoAnimationLooped;
  char TorsoAnimationReset;
} DZStrikerMobVars_t;

typedef struct DZStrikerTorsoPVar {
	struct TargetVars * TargetVarsPtr;
	char _pad0[0x0C];
	struct ReactVars * ReactVarsPtr;
	char _pad1[0x08];
  struct MoveVars_V2 * MoveVarsPtr;
	char _pad2[0x14];
 	struct FlashVars * FlashVarsPtr;
	char _pad3[0x14];
 	void * AdditionalMobVarsPtr;

	struct TargetVars TargetVars;
	struct FlashVars FlashVars;
} DZStrikerTorsoPVar_t;

int dzstrikerCreate(struct MobCreateArgs* args);

#endif // RAIDS_MOB_DZSTRIKER_H
