#ifndef RAIDS_MOB_LEVIATHAN_H
#define RAIDS_MOB_LEVIATHAN_H

#include "game.h"

#define LEVIATHAN_RENDER_COST                    (200)

#define LEVIATHAN_BASE_REACTION_TICKS						(0.25 * TPS)
#define LEVIATHAN_BASE_ATTACK_COOLDOWN_TICKS			(2 * TPS)
#define LEVIATHAN_BASE_EXPLODE_RADIUS						(5)
#define LEVIATHAN_MELEE_HIT_RADIUS								(0.5)
#define LEVIATHAN_EXPLODE_HIT_RADIUS							(5)
#define LEVIATHAN_CHASE_TARGET_RADIUS						 (20.0)
#define LEVIATHAN_CHASE_MAX_OUT_OF_SIGHT_TICKS	 (10*TPS)
#define LEVIATHAN_CHASE_SPEED_MULT	             (2.0)
#define LEVIATHAN_EVADE_MAX_OUT_OF_SIGHT_TICKS	 (TPS)
#define LEVIATHAN_EVADE_COOLDOWN_TICKS	         (5 * TPS)

#define LEVIATHAN_TARGET_KEEP_CURRENT_FACTOR     (3)

#define LEVIATHAN_MAX_WALKABLE_SLOPE             (40 * MATH_DEG2RAD)
#define LEVIATHAN_BASE_STEP_HEIGHT								(2)
#define LEVIATHAN_TURN_RADIANS_PER_SEC           (90 * MATH_DEG2RAD)
#define LEVIATHAN_TURN_AIR_RADIANS_PER_SEC       (45 * MATH_DEG2RAD)
#define LEVIATHAN_MOVE_ACCELERATION              (25)
#define LEVIATHAN_MOVE_AIR_ACCELERATION          (5)
#define LEVIATHAN_MOVE_STRAFE_MULT               (0.5)

#define LEVIATHAN_ANIM_ATTACK_TICKS							(30)
#define LEVIATHAN_FLINCH_COOLDOWN_TICKS					(60 * 7)
#define LEVIATHAN_KNOCKBACK_MULTIPLIER				    (1.5)
#define LEVIATHAN_ACTION_COOLDOWN_TICKS					(30)
#define LEVIATHAN_RESPAWN_AFTER_TICKS						(60 * 30)
#define LEVIATHAN_BASE_COLL_RADIUS								(1.0)
#define LEVIATHAN_MAX_COLL_RADIUS								(4)
#define LEVIATHAN_AMBSND_MIN_COOLDOWN_TICKS    	(60 * 2)
#define LEVIATHAN_AMBSND_MAX_COOLDOWN_TICKS    	(60 * 3)
#define LEVIATHAN_FLINCH_PROBABILITY             (1.0)
#define LEVIATHAN_FLINCH_PROBABILITY_PWR_FACTOR  (0.1)

#define LEVIATHAN_LASER_EXHAUSTED_ANIM_LOOP      (2)
#define LEVIATHAN_LASER_FIRE_FOR_TICKS           (3 * TPS)
#define LEVIATHAN_LASER_FIRE_CYCLE_TICKS         (0.5 * TPS)
#define LEVIATHAN_LASER_MAX_ANGLE                (80 * MATH_DEG2RAD)
#define LEVIATHAN_LASER_COOLDOWN_TICKS_MIN       (2 * TPS)
#define LEVIATHAN_LASER_COOLDOWN_TICKS_MAX       (20 * TPS)

#define LEVIATHAN_PRIMARY_COLOR                  (0x00464443)
#define LEVIATHAN_GLOW_COLOR                     (0x80202020)
#define LEVIATHAN_LOD_COLOR                      (0x00808080)

enum LeviathanAnimId
{
	LEVIATHAN_ANIM_IDLE,
	LEVIATHAN_ANIM_LOOK_AROUND,
	LEVIATHAN_ANIM_LOOK_AROUND_2,
	LEVIATHAN_ANIM_WALK,
	LEVIATHAN_ANIM_WALK_BACKWARDS,
	LEVIATHAN_ANIM_WALK_RIGHT,
	LEVIATHAN_ANIM_WALK_LEFT,
	LEVIATHAN_ANIM_7,
	LEVIATHAN_ANIM_8,
	LEVIATHAN_ANIM_JUMP,
	LEVIATHAN_ANIM_FIRE_ENTER,
	LEVIATHAN_ANIM_FIRE_ACTIVE,
	LEVIATHAN_ANIM_FIRE_RELEASE,
	LEVIATHAN_ANIM_LASER_FIRE_BEGIN,
	LEVIATHAN_ANIM_LASER_FIRE_EXHAUSTED,
	LEVIATHAN_ANIM_LASER_FIRE_ACTIVE,
	LEVIATHAN_ANIM_LASER_FIRE_ACTIVE_WALK,
	LEVIATHAN_ANIM_FLINCH,
	LEVIATHAN_ANIM_BIG_FLINCH,
	LEVIATHAN_ANIM_HUGE_FLINCH,
	LEVIATHAN_ANIM_DIE,
	LEVIATHAN_ANIM_SWING,
	LEVIATHAN_ANIM_STAB_DOWN,
	LEVIATHAN_ANIM_23,
	LEVIATHAN_ANIM_24,
	LEVIATHAN_ANIM_TAIL_EMERGE_FROM_WATER,
	LEVIATHAN_ANIM_TAIL_IDLE,
	LEVIATHAN_ANIM_TAIL_LOOK_AROUND,
	LEVIATHAN_ANIM_TAIL_FIRE_ENTER,
	LEVIATHAN_ANIM_TAIL_FIRE_ACTIVE,
	LEVIATHAN_ANIM_TAIL_FIRE_RELEASE,
	LEVIATHAN_ANIM_TAIL_FLINCH,
	LEVIATHAN_ANIM_TAIL_EXHAUSTED,
	LEVIATHAN_ANIM_TAIL_LASER_ACTIVE,
	LEVIATHAN_ANIM_TAIL_34,
	LEVIATHAN_ANIM_TAIL_BIG_FLINCH,
};

enum LeviathanAction
{
	LEVIATHAN_ACTION_SPAWN,
	LEVIATHAN_ACTION_IDLE,
	LEVIATHAN_ACTION_JUMP,
	LEVIATHAN_ACTION_WALK,
	LEVIATHAN_ACTION_CHASE,
	LEVIATHAN_ACTION_STRAFE,
	LEVIATHAN_ACTION_FLINCH,
	LEVIATHAN_ACTION_BIG_FLINCH,
	LEVIATHAN_ACTION_LOOK_AT_TARGET,
  LEVIATHAN_ACTION_DIE,
	LEVIATHAN_ACTION_ATTACK_SWING,
	LEVIATHAN_ACTION_ATTACK_STAB,
	LEVIATHAN_ACTION_ATTACK_PROJECTILE,
	LEVIATHAN_ACTION_ATTACK_LASER,
	LEVIATHAN_ACTION_ATTACK_LASER_LOCKON,
	LEVIATHAN_ACTION_ROAM,
};

enum LeviathanSubskeletonJoints
{
  LEVIATHAN_SUBSKELETON_JOINT_TAIL_HEAD = 0,
  LEVIATHAN_SUBSKELETON_JOINT_TAIL_BASE = 1,
  LEVIATHAN_SUBSKELETON_JOINT_TAIL_KNUCKLE_1 = 2,
  LEVIATHAN_SUBSKELETON_JOINT_BODY = 3,
};

enum LeviathanBehaviorId
{
	LEVIATHAN_BEHAVIOR_NORMAL,
	LEVIATHAN_BEHAVIOR_AGGRESSIVE,
	LEVIATHAN_BEHAVIOR_EVASIVE,
};

typedef struct LeviathanMobVars {
  VECTOR LaserbeamDirection;
  VECTOR LaserbeamTarget1;
  VECTOR LaserbeamTarget2;
  Moby* LaserbeamMoby;
  u32 AttackLaserCooldownTicks;
  int LaserAtTicks;
} LeviathanMobVars_t;

extern struct MobVTable LeviathanVTable;

int leviathanCreate(struct MobCreateArgs* args);

#endif // RAIDS_MOB_LEVIATHAN_H
