#ifndef RAIDS_MOB_SWAMPER_H
#define RAIDS_MOB_SWAMPER_H

#include "game.h"

#define SWAMPER_RENDER_COST                   (40)

#define SWAMPER_BASE_REACTION_TICKS						(0.25 * TPS)
#define SWAMPER_BASE_ATTACK_COOLDOWN_TICKS		(2 * TPS)
#define SWAMPER_BASE_EXPLODE_RADIUS						(5)
#define SWAMPER_MELEE_HIT_RADIUS							(1.75)
#define SWAMPER_EXPLODE_HIT_RADIUS						(5)
#define SWAMPER_MELEE_ATTACK_RADIUS						(5)

#define SWAMPER_TARGET_KEEP_CURRENT_FACTOR    (3)

#define SWAMPER_MAX_WALKABLE_SLOPE            (40 * MATH_DEG2RAD)
#define SWAMPER_BASE_STEP_HEIGHT							(2)
#define SWAMPER_TURN_RADIANS_PER_SEC          (90 * MATH_DEG2RAD)
#define SWAMPER_TURN_AIR_RADIANS_PER_SEC      (45 * MATH_DEG2RAD)
#define SWAMPER_MOVE_ACCELERATION             (25)
#define SWAMPER_MOVE_AIR_ACCELERATION         (5)

#define SWAMPER_ANIM_ATTACK_TICKS							(30)
#define SWAMPER_FLINCH_COOLDOWN_TICKS				  (60 * 7)
#define SWAMPER_KNOCKBACK_MULTIPLIER				  (2.0)
#define SWAMPER_ACTION_COOLDOWN_TICKS					(30)
#define SWAMPER_RESPAWN_AFTER_TICKS						(60 * 30)
#define SWAMPER_BASE_COLL_RADIUS							(0.5)
#define SWAMPER_MAX_COLL_RADIUS								(4)
#define SWAMPER_AMBSND_MIN_COOLDOWN_TICKS    	(60 * 2)
#define SWAMPER_AMBSND_MAX_COOLDOWN_TICKS    	(60 * 3)
#define SWAMPER_FLINCH_PROBABILITY            (1.0)
#define SWAMPER_FLINCH_PROBABILITY_PWR_FACTOR (0.1)

#define SWAMPER_PRIMARY_COLOR                  (0x00464443)
#define SWAMPER_GLOW_COLOR                     (0x80202020)
#define SWAMPER_LOD_COLOR                      (0x00808080)

enum SwamperAnimId
{
	SWAMPER_ANIM_IDLE,
	SWAMPER_ANIM_SPAWN,
	SWAMPER_ANIM_DIG_INTO_GROUND,
	SWAMPER_ANIM_LOOK_RIGHT_LEFT_ROAR,
	SWAMPER_ANIM_SNIFF_LEFT_RIGHT,
	SWAMPER_ANIM_BITE,
	SWAMPER_ANIM_ROAR,
	SWAMPER_ANIM_JUMP,
	SWAMPER_ANIM_WALK,
	SWAMPER_ANIM_RUN,
	SWAMPER_ANIM_JUMP_BACKWARDS,
	SWAMPER_ANIM_FALL_BACKWARDS,
};

enum SwamperAction
{
	SWAMPER_ACTION_SPAWN,
	SWAMPER_ACTION_IDLE,
	SWAMPER_ACTION_JUMP,
	SWAMPER_ACTION_WALK,
	SWAMPER_ACTION_FLINCH,
	SWAMPER_ACTION_BIG_FLINCH,
	SWAMPER_ACTION_LOOK_AT_TARGET,
  SWAMPER_ACTION_DIE,
	SWAMPER_ACTION_ATTACK,
  SWAMPER_ACTION_ROAM
};

enum SwamperSubskeletonJoints
{
  SWAMPER_SUBSKELETON_JOINT_JAW = 0,
};

extern struct MobVTable SwamperVTable;

int swamperCreate(struct MobCreateArgs* args);

#endif // RAIDS_MOB_SWAMPER_H
