#ifndef SURVIVAL_MOB_LEVIATHAN_H
#define SURVIVAL_MOB_LEVIATHAN_H

#define LEVIATHAN_BASE_REACTION_TICKS (0.25 * TPS)
#define LEVIATHAN_BASE_ATTACK_COOLDOWN_TICKS (2 * TPS)
#define LEVIATHAN_BASE_EXPLODE_RADIUS (5)
#define LEVIATHAN_MELEE_HIT_RADIUS (0.5)
#define LEVIATHAN_EXPLODE_HIT_RADIUS (5)
#define LEVIATHAN_MELEE_ATTACK_RADIUS (3.5)
#define LEVIATHAN_CHASE_TARGET_RADIUS (30.0)
#define LEVIATHAN_CHASE_MAX_OUT_OF_SIGHT_TICKS (10 * TPS)
#define LEVIATHAN_CHASE_SPEED_MULT (2.0)
#define LEVIATHAN_EVADE_MAX_OUT_OF_SIGHT_TICKS (TPS)
#define LEVIATHAN_EVADE_COOLDOWN_TICKS (5 * TPS)
#define LEVIATHAN_VISION_RANGE (50.0)

#define LEVIATHAN_TARGET_KEEP_CURRENT_FACTOR (3)

#define LEVIATHAN_MAX_WALKABLE_SLOPE (40 * MATH_DEG2RAD)
#define LEVIATHAN_BASE_STEP_HEIGHT (2)
#define LEVIATHAN_TURN_RADIANS_PER_SEC (90 * MATH_DEG2RAD)
#define LEVIATHAN_TURN_AIR_RADIANS_PER_SEC (45 * MATH_DEG2RAD)
#define LEVIATHAN_MOVE_ACCELERATION (25)
#define LEVIATHAN_MOVE_AIR_ACCELERATION (5)
#define LEVIATHAN_MOVE_STRAFE_MULT (0.5)

#define LEVIATHAN_DEFAULT_JUMP_SPEED (8)

// AnimSeqT range defines for animation state checks
#define LEVIATHAN_SWING_ATTACK_HIT_FRAME_START (15)
#define LEVIATHAN_SWING_ATTACK_HIT_FRAME_END (18)
#define LEVIATHAN_STAB_ATTACK_HIT_FRAME_START (4.5)
#define LEVIATHAN_STAB_ATTACK_HIT_FRAME_END (6)
#define LEVIATHAN_JUMP_ANIM_DURATION (35)
#define LEVIATHAN_FLINCH_ANIM_DURATION (20)

#define LEVIATHAN_ANIM_ATTACK_TICKS (30)
#define LEVIATHAN_FLINCH_COOLDOWN_TICKS (60 * 7)
#define LEVIATHAN_KNOCKBACK_MULTIPLIER (0.5)
#define LEVIATHAN_STATE_COOLDOWN_TICKS (30)
#define LEVIATHAN_RESPAWN_AFTER_TICKS (60 * 30)
#define LEVIATHAN_BASE_COLL_RADIUS (2.0)
#define LEVIATHAN_MAX_COLL_RADIUS (4)
#define LEVIATHAN_AMBSND_MIN_COOLDOWN_TICKS (60 * 2)
#define LEVIATHAN_AMBSND_MAX_COOLDOWN_TICKS (60 * 3)
#define LEVIATHAN_FLINCH_PROBABILITY (1.0)
#define LEVIATHAN_FLINCH_PROBABILITY_PWR_FACTOR (0.1)

#define LEVIATHAN_LASER_EXHAUSTED_ANIM_LOOP (2)
#define LEVIATHAN_LASER_FIRE_FOR_TICKS (3 * TPS)
#define LEVIATHAN_LASER_FIRE_CYCLE_TICKS (0.5 * TPS)
#define LEVIATHAN_LASER_MAX_ANGLE (80 * MATH_DEG2RAD)
#define LEVIATHAN_LASER_COOLDOWN_TICKS_MIN (2 * TPS)
#define LEVIATHAN_LASER_COOLDOWN_TICKS_MAX (20 * TPS)

#define LEVIATHAN_PRIMARY_COLOR (0x00464443)
#define LEVIATHAN_GLOW_COLOR (0x80FF2020)
#define LEVIATHAN_LOD_COLOR (0x0000FF00)

#include <libdl/math3d.h>
#include <libdl/moby.h>

enum LeviathanAnimId
{
	LEVIATHAN_ANIM_IDLE,
	LEVIATHAN_ANIM_LOOK_AROUND,
	LEVIATHAN_ANIM_LOOK_AROUND_2,
	LEVIATHAN_ANIM_WALK,
	LEVIATHAN_ANIM_WALK_BACKWARDS,
	LEVIATHAN_ANIM_WALK_RIGHT,
	LEVIATHAN_ANIM_WALK_LEFT,
	LEVIATHAN_ANIM_7,
	LEVIATHAN_ANIM_8,
	LEVIATHAN_ANIM_JUMP,
	LEVIATHAN_ANIM_FIRE_ENTER,
	LEVIATHAN_ANIM_FIRE_ACTIVE,
	LEVIATHAN_ANIM_FIRE_RELEASE,
	LEVIATHAN_ANIM_LASER_FIRE_BEGIN,
	LEVIATHAN_ANIM_LASER_FIRE_EXHAUSTED,
	LEVIATHAN_ANIM_LASER_FIRE_ACTIVE,
	LEVIATHAN_ANIM_LASER_FIRE_ACTIVE_WALK,
	LEVIATHAN_ANIM_FLINCH,
	LEVIATHAN_ANIM_BIG_FLINCH,
	LEVIATHAN_ANIM_HUGE_FLINCH,
	LEVIATHAN_ANIM_DIE,
	LEVIATHAN_ANIM_SWING,
	LEVIATHAN_ANIM_STAB_DOWN,
	LEVIATHAN_ANIM_23,
	LEVIATHAN_ANIM_24,
	LEVIATHAN_ANIM_TAIL_EMERGE_FROM_WATER,
	LEVIATHAN_ANIM_TAIL_IDLE,
	LEVIATHAN_ANIM_TAIL_LOOK_AROUND,
	LEVIATHAN_ANIM_TAIL_FIRE_ENTER,
	LEVIATHAN_ANIM_TAIL_FIRE_ACTIVE,
	LEVIATHAN_ANIM_TAIL_FIRE_RELEASE,
	LEVIATHAN_ANIM_TAIL_FLINCH,
	LEVIATHAN_ANIM_TAIL_EXHAUSTED,
	LEVIATHAN_ANIM_TAIL_LASER_ACTIVE,
	LEVIATHAN_ANIM_TAIL_34,
	LEVIATHAN_ANIM_TAIL_BIG_FLINCH,
};

enum LeviathanStates
{
	LEVIATHAN_STATE_SPAWN,
	LEVIATHAN_STATE_IDLE,
	LEVIATHAN_STATE_JUMP,
	LEVIATHAN_STATE_WALK,
	LEVIATHAN_STATE_CHASE,
	LEVIATHAN_STATE_STRAFE,
	LEVIATHAN_STATE_FLINCH,
	LEVIATHAN_STATE_BIG_FLINCH,
	LEVIATHAN_STATE_LOOK_AT_TARGET,
	LEVIATHAN_STATE_DIE,
	LEVIATHAN_STATE_ATTACK_SWING,
	LEVIATHAN_STATE_ATTACK_STAB,
	LEVIATHAN_STATE_ATTACK_PROJECTILE,
	LEVIATHAN_STATE_ATTACK_LASER,
	LEVIATHAN_STATE_ATTACK_LASER_LOCKON,
};

enum LeviathanSubskeletonJoints
{
	LEVIATHAN_SUBSKELETON_JOINT_TAIL_HEAD = 0,
	LEVIATHAN_SUBSKELETON_JOINT_TAIL_BASE = 1,
	LEVIATHAN_SUBSKELETON_JOINT_TAIL_KNUCKLE_1 = 2,
	LEVIATHAN_SUBSKELETON_JOINT_BODY = 3,
};

enum LeviathanBehaviors
{
	LEVIATHAN_BEHAVIOR_NORMAL = 0,
	LEVIATHAN_BEHAVIOR_MELEE = 1,
	LEVIATHAN_BEHAVIOR_RANGED = 2,
};

typedef struct LeviathanMobVars
{
	VECTOR LaserbeamDirection;
	VECTOR LaserbeamTarget1;
	VECTOR LaserbeamTarget2;
	Moby *LaserbeamMoby;
	u32 AttackLaserCooldownTicks;
	int LaserAtTicks;
} LeviathanMobVars_t;

struct MobConfig;

extern struct MobVTable LeviathanVTable;

#endif // SURVIVAL_MOB_LEVIATHAN_H
