#ifndef SURVIVAL_MOB_SWAMPER_H
#define SURVIVAL_MOB_SWAMPER_H

#include "game.h"

#define SWAMPER_RENDER_COST (40)

#define SWAMPER_BASE_REACTION_TICKS (0.25 * TPS)
#define SWAMPER_BASE_ATTACK_COOLDOWN_TICKS (2 * TPS)
#define SWAMPER_BASE_EXPLODE_RADIUS (5)
#define SWAMPER_MELEE_HIT_RADIUS (1.75)
#define SWAMPER_EXPLODE_HIT_RADIUS (5)
#define SWAMPER_MELEE_ATTACK_RADIUS (5)

#define SWAMPER_TARGET_KEEP_CURRENT_FACTOR (3)

#define SWAMPER_MAX_WALKABLE_SLOPE (40 * MATH_DEG2RAD)
#define SWAMPER_BASE_STEP_HEIGHT (2)
#define SWAMPER_TURN_RADIANS_PER_SEC (90 * MATH_DEG2RAD)
#define SWAMPER_TURN_AIR_RADIANS_PER_SEC (45 * MATH_DEG2RAD)
#define SWAMPER_MOVE_ACCELERATION (25)
#define SWAMPER_MOVE_AIR_ACCELERATION (5)

#define SWAMPER_DEFAULT_JUMP_SPEED (8)

// AnimSeqT range defines for animation state checks
#define SWAMPER_JUMP_ANIM_DURATION (35)
#define SWAMPER_FLINCH_ANIM_AIR_DURATION (20)
#define SWAMPER_BITE_ANIM_DURATION (42)
#define SWAMPER_BITE_LUNGE_FRAME_START (15)
#define SWAMPER_BITE_LUNGE_FRAME_END (30)
#define SWAMPER_BITE_ATTACK_HIT_FRAME_START (22)
#define SWAMPER_BITE_ATTACK_HIT_FRAME_END (30)

#define SWAMPER_ANIM_ATTACK_TICKS (30)
#define SWAMPER_FLINCH_COOLDOWN_TICKS (60 * 7)
#define SWAMPER_KNOCKBACK_MULTIPLIER (1.5)
#define SWAMPER_STATE_COOLDOWN_TICKS (30)
#define SWAMPER_RESPAWN_AFTER_TICKS (60 * 30)
#define SWAMPER_BASE_COLL_RADIUS (0.5)
#define SWAMPER_MAX_COLL_RADIUS (4)
#define SWAMPER_AMBSND_MIN_COOLDOWN_TICKS (60 * 2)
#define SWAMPER_AMBSND_MAX_COOLDOWN_TICKS (60 * 3)
#define SWAMPER_FLINCH_PROBABILITY (1.0)
#define SWAMPER_FLINCH_PROBABILITY_PWR_FACTOR (0.1)

#define SWAMPER_PRIMARY_COLOR (0x00464443)
#define SWAMPER_GLOW_COLOR (0x80202020)
#define SWAMPER_LOD_COLOR (0x00808080)

enum SwamperAnimId
{
	SWAMPER_ANIM_IDLE,
	SWAMPER_ANIM_SPAWN,
	SWAMPER_ANIM_DIG_INTO_GROUND,
	SWAMPER_ANIM_LOOK_RIGHT_LEFT_ROAR,
	SWAMPER_ANIM_SNIFF_LEFT_RIGHT,
	SWAMPER_ANIM_BITE,
	SWAMPER_ANIM_ROAR,
	SWAMPER_ANIM_JUMP,
	SWAMPER_ANIM_WALK,
	SWAMPER_ANIM_RUN,
	SWAMPER_ANIM_JUMP_BACKWARDS,
	SWAMPER_ANIM_FALL_BACKWARDS,
};

enum SwamperStates
{
	SWAMPER_STATE_SPAWN,
	SWAMPER_STATE_IDLE,
	SWAMPER_STATE_JUMP,
	SWAMPER_STATE_WALK,
	SWAMPER_STATE_FLINCH,
	SWAMPER_STATE_BIG_FLINCH,
	SWAMPER_STATE_LOOK_AT_TARGET,
	SWAMPER_STATE_DIE,
	SWAMPER_STATE_ATTACK,
	SWAMPER_STATE_ROAM
};

enum SwamperSubskeletonJoints
{
	SWAMPER_SUBSKELETON_JOINT_JAW = 0,
};

struct MobConfig;

extern struct MobVTable SwamperVTable;

#endif // SURVIVAL_MOB_SWAMPER_H
