#ifndef SURVIVAL_MOB_EXECUTIONER2_H
#define SURVIVAL_MOB_EXECUTIONER2_H

#define EXECUTIONER2_BASE_REACTION_TICKS						  (0.25 * TPS)
#define EXECUTIONER2_BASE_ATTACK_COOLDOWN_TICKS			(5 * TPS)
#define EXECUTIONER2_BASE_EXPLODE_RADIUS						  (5)
#define EXECUTIONER2_MELEE_HIT_RADIUS								(1.00)
#define EXECUTIONER2_EXPLODE_HIT_RADIUS							(5)
#define EXECUTIONER2_MELEE_ATTACK_RADIUS						  (4)
#define EXECUTIONER2_TOO_CLOSE_TO_TARGET_RADIUS		  (2.5)
#define EXECUTIONER2_VISION_RANGE                    (50.0)

#define EXECUTIONER2_HIT_INV_TICKS                   (0.1 * TPS)

#define EXECUTIONER2_TARGET_KEEP_CURRENT_FACTOR      (3)

#define EXECUTIONER2_MAX_WALKABLE_SLOPE              (40 * MATH_DEG2RAD)
#define EXECUTIONER2_BASE_STEP_HEIGHT								(2)
#define EXECUTIONER2_TURN_RADIANS_PER_SEC            (45 * MATH_DEG2RAD)
#define EXECUTIONER2_TURN_AIR_RADIANS_PER_SEC        (15 * MATH_DEG2RAD)
#define EXECUTIONER2_MOVE_ACCELERATION               (25)
#define EXECUTIONER2_MOVE_AIR_ACCELERATION           (5)

#define EXECUTIONER2_ANIM_ATTACK_TICKS							  (30)
#define EXECUTIONER2_TIMEBOMB_TICKS									(60 * 2)
#define EXECUTIONER2_FLINCH_COOLDOWN_TICKS					  (60 * 7)
#define EXECUTIONER2_KNOCKBACK_MULTIPLIER				    (0.0)
#define EXECUTIONER2_ACTION_COOLDOWN_TICKS					  (30)
#define EXECUTIONER2_RESPAWN_AFTER_TICKS						  (60 * 30)
#define EXECUTIONER2_BASE_COLL_RADIUS								(0.5)
#define EXECUTIONER2_MAX_COLL_RADIUS								  (4)
#define EXECUTIONER2_AMBSND_MIN_COOLDOWN_TICKS    	  (60 * 2)
#define EXECUTIONER2_AMBSND_MAX_COOLDOWN_TICKS    	  (60 * 3)
#define EXECUTIONER2_FLINCH_PROBABILITY              (0.05)
#define EXECUTIONER2_FLINCH_PROBABILITY_PWR_FACTOR   (0.02)

#define EXECUTIONER2_PRIMARY_COLOR                  (0x00464443)
#define EXECUTIONER2_GLOW_COLOR                     (0x80202020)
#define EXECUTIONER2_LOD_COLOR                      (0x000000FF)

enum Executioner2AnimId
{
  EXECUTIONER2_ANIM_IDLE,
  EXECUTIONER2_ANIM_LOOK_ON_ALERT,
  EXECUTIONER2_ANIM_STOMP_ON_GROUND,
  EXECUTIONER2_ANIM_WALK,
  EXECUTIONER2_ANIM_WALK_BACKWARD,
  EXECUTIONER2_ANIM_RUN,
  EXECUTIONER2_ANIM_JUMP,
  EXECUTIONER2_ANIM_SWING,
  EXECUTIONER2_ANIM_THROW,
  EXECUTIONER2_ANIM_FIRE,
  EXECUTIONER2_ANIM_CELEBRATE,
  EXECUTIONER2_ANIM_FLINCH,
  EXECUTIONER2_ANIM_BIG_FLINCH,
  EXECUTIONER2_ANIM_FLINCH_FALL_DOWN,
  EXECUTIONER2_ANIM_SPAWN
};

enum Executioner2Bangles {
  EXECUTIONER2_BANGLE_LEFT_CHEST_PLATE =  	  (1 << 0),
  EXECUTIONER2_BANGLE_RIGHT_CHEST_PLATE =  	(1 << 1),
  EXECUTIONER2_BANGLE_HELMET =  	            (1 << 2),
  EXECUTIONER2_BANGLE_LEFT_COLLAR_BONE =  	  (1 << 3),
  EXECUTIONER2_BANGLE_RIGHT_COLLAR_BONE =  	(1 << 4),
  EXECUTIONER2_BANGLE_BRAIN =  	            (1 << 5),
  EXECUTIONER2_BANGLE_HIDE_BODY =	          (1 << 15)
};

enum Executioner2Action
{
  EXECUTIONER2_ACTION_SPAWN,
  EXECUTIONER2_ACTION_IDLE,
  EXECUTIONER2_ACTION_JUMP,
  EXECUTIONER2_ACTION_WALK,
  EXECUTIONER2_ACTION_FLINCH,
  EXECUTIONER2_ACTION_BIG_FLINCH,
  EXECUTIONER2_ACTION_LOOK_AT_TARGET,
  EXECUTIONER2_ACTION_DIE,
  EXECUTIONER2_ACTION_ATTACK,
  EXECUTIONER2_ACTION_FIRE
};

enum Executioner2SubskeletonJoints
{
  EXECUTIONER2_SUBSKELETON_JOINT_ABDOMEN = 0,
  EXECUTIONER2_SUBSKELETON_JOINT_CHEST,
  EXECUTIONER2_SUBSKELETON_JOINT_HEAD,
  EXECUTIONER2_SUBSKELETON_JOINT_RIGHT_SHOULDER,
  EXECUTIONER2_SUBSKELETON_JOINT_RIGHT_HAND,
  EXECUTIONER2_SUBSKELETON_JOINT_RIGHT_PALM,
  EXECUTIONER2_SUBSKELETON_JOINT_STAFF_END,
  EXECUTIONER2_SUBSKELETON_JOINT_LEFT_HAND,
  EXECUTIONER2_SUBSKELETON_JOINT_HIPS,
};

typedef struct Executioner2MobVars
{
  int AnimationLoopLastFire;
  u8 LocalPlayerDamageHitInvTimer[GAME_MAX_LOCALS];
} Executioner2MobVars_t;

struct MobConfig;
int executioner2Create(int spawnParamsIdx, VECTOR position, float yaw, int spawnFromUID, int spawnFlags, struct MobConfig *config);

extern struct MobVTable Executioner2VTable;

#endif // SURVIVAL_MOB_EXECUTIONER2_H
