#ifndef SURVIVAL_MOB_EXECUTIONER_H
#define SURVIVAL_MOB_EXECUTIONER_H

#define EXECUTIONER_BASE_REACTION_TICKS						  (0.25 * TPS)
#define EXECUTIONER_BASE_ATTACK_COOLDOWN_TICKS			(5 * TPS)
#define EXECUTIONER_BASE_EXPLODE_RADIUS						  (5)
#define EXECUTIONER_MELEE_HIT_RADIUS								(1.00)
#define EXECUTIONER_EXPLODE_HIT_RADIUS							(5)
#define EXECUTIONER_MELEE_ATTACK_RADIUS						  (4)
#define EXECUTIONER_TOO_CLOSE_TO_TARGET_RADIUS		  (2.5)
#define EXECUTIONER_VISION_RANGE                    (50.0)

#define EXECUTIONER_HIT_INV_TICKS                   (0.1 * TPS)

#define EXECUTIONER_TARGET_KEEP_CURRENT_FACTOR      (3)

#define EXECUTIONER_MAX_WALKABLE_SLOPE              (40 * MATH_DEG2RAD)
#define EXECUTIONER_BASE_STEP_HEIGHT								(2)
#define EXECUTIONER_TURN_RADIANS_PER_SEC            (45 * MATH_DEG2RAD)
#define EXECUTIONER_TURN_AIR_RADIANS_PER_SEC        (15 * MATH_DEG2RAD)
#define EXECUTIONER_MOVE_ACCELERATION               (25)
#define EXECUTIONER_MOVE_AIR_ACCELERATION           (5)

#define EXECUTIONER_ANIM_ATTACK_TICKS							  (30)
#define EXECUTIONER_TIMEBOMB_TICKS									(60 * 2)
#define EXECUTIONER_FLINCH_COOLDOWN_TICKS					  (60 * 7)
#define EXECUTIONER_KNOCKBACK_MULTIPLIER				    (0.0)
#define EXECUTIONER_ACTION_COOLDOWN_TICKS					  (30)
#define EXECUTIONER_RESPAWN_AFTER_TICKS						  (60 * 30)
#define EXECUTIONER_BASE_COLL_RADIUS								(0.5)
#define EXECUTIONER_MAX_COLL_RADIUS								  (4)
#define EXECUTIONER_AMBSND_MIN_COOLDOWN_TICKS    	  (60 * 2)
#define EXECUTIONER_AMBSND_MAX_COOLDOWN_TICKS    	  (60 * 3)
#define EXECUTIONER_FLINCH_PROBABILITY              (0.05)
#define EXECUTIONER_FLINCH_PROBABILITY_PWR_FACTOR   (0.02)

#define EXECUTIONER_PRIMARY_COLOR                  (0x00464443)
#define EXECUTIONER_GLOW_COLOR                     (0x80202020)
#define EXECUTIONER_LOD_COLOR                      (0x000000FF)

enum ExecutionerAnimId
{
  EXECUTIONER_ANIM_IDLE,
  EXECUTIONER_ANIM_LOOK_ON_ALERT,
  EXECUTIONER_ANIM_STOMP_ON_GROUND,
  EXECUTIONER_ANIM_WALK,
  EXECUTIONER_ANIM_WALK_BACKWARD,
  EXECUTIONER_ANIM_RUN,
  EXECUTIONER_ANIM_JUMP,
  EXECUTIONER_ANIM_SWING,
  EXECUTIONER_ANIM_THROW,
  EXECUTIONER_ANIM_FIRE,
  EXECUTIONER_ANIM_CELEBRATE,
  EXECUTIONER_ANIM_FLINCH,
  EXECUTIONER_ANIM_BIG_FLINCH,
  EXECUTIONER_ANIM_FLINCH_FALL_DOWN,
  EXECUTIONER_ANIM_SPAWN
};

enum ExecutionerBangles {
  EXECUTIONER_BANGLE_LEFT_CHEST_PLATE =  	  (1 << 0),
  EXECUTIONER_BANGLE_RIGHT_CHEST_PLATE =  	(1 << 1),
  EXECUTIONER_BANGLE_HELMET =  	            (1 << 2),
  EXECUTIONER_BANGLE_LEFT_COLLAR_BONE =  	  (1 << 3),
  EXECUTIONER_BANGLE_RIGHT_COLLAR_BONE =  	(1 << 4),
  EXECUTIONER_BANGLE_BRAIN =  	            (1 << 5),
  EXECUTIONER_BANGLE_HIDE_BODY =	          (1 << 15)
};

enum ExecutionerAction
{
  EXECUTIONER_ACTION_SPAWN,
  EXECUTIONER_ACTION_IDLE,
  EXECUTIONER_ACTION_JUMP,
  EXECUTIONER_ACTION_WALK,
  EXECUTIONER_ACTION_FLINCH,
  EXECUTIONER_ACTION_BIG_FLINCH,
  EXECUTIONER_ACTION_LOOK_AT_TARGET,
  EXECUTIONER_ACTION_DIE,
  EXECUTIONER_ACTION_ATTACK,
  EXECUTIONER_ACTION_FIRE
};

enum ExecutionerSubskeletonJoints
{
  EXECUTIONER_SUBSKELETON_JOINT_ABDOMEN = 0,
  EXECUTIONER_SUBSKELETON_JOINT_CHEST,
  EXECUTIONER_SUBSKELETON_JOINT_HEAD,
  EXECUTIONER_SUBSKELETON_JOINT_RIGHT_SHOULDER,
  EXECUTIONER_SUBSKELETON_JOINT_RIGHT_HAND,
  EXECUTIONER_SUBSKELETON_JOINT_RIGHT_PALM,
  EXECUTIONER_SUBSKELETON_JOINT_STAFF_END,
  EXECUTIONER_SUBSKELETON_JOINT_LEFT_HAND,
  EXECUTIONER_SUBSKELETON_JOINT_HIPS,
};

typedef struct ExecutionerMobVars
{
  int AnimationLoopLastFire;
  u8 LocalPlayerDamageHitInvTimer[GAME_MAX_LOCALS];
} ExecutionerMobVars_t;

struct MobConfig;
int executionerCreate(int spawnParamsIdx, VECTOR position, float yaw, int spawnFromUID, int spawnFlags, struct MobConfig *config);

extern struct MobVTable ExecutionerVTable;

#endif // SURVIVAL_MOB_EXECUTIONER_H
